export const pages = [
  {
    id: 'home', preset: {},
    vi: { path: '/', title: 'Nén ảnh online miễn phí — JPG, PNG, WebP | Ảnh Gọn', h1: 'Nén ảnh miễn phí, ngay trên thiết bị.', description: 'Nén ảnh, giảm dung lượng JPG, PNG, WebP và đổi HEIC sang JPG ngay trên thiết bị. Miễn phí, xử lý nhiều ảnh, không cần tài khoản.', intro: 'Nén, đổi định dạng và thu nhỏ nhiều ảnh ngay trong trình duyệt. Chọn ảnh, xem kết quả và tải về — ảnh của bạn không được gửi lên server.', label: 'Nén ảnh online', steps: ['Chọn chất lượng, định dạng và giới hạn kích thước nếu cần.', 'Thêm một hoặc nhiều ảnh. Công cụ xử lý lần lượt ngay trên thiết bị.', 'Kiểm tra dung lượng và ảnh xem trước, rồi tải từng ảnh hoặc ZIP.'], notes: ['Dùng JPG cho ảnh chụp; PNG cho đồ họa cần nền trong suốt; WebP cho website.', 'Giảm dung lượng và giảm số pixel là hai việc khác nhau. Có thể kết hợp khi ảnh vẫn quá lớn.', 'Giữ bản gốc: nén có thể làm mất chi tiết, EXIF bị loại bỏ và ảnh động thành ảnh tĩnh.'], faq: [['Có nén ảnh xuống 200 KB không?', 'Chọn chế độ theo dung lượng hoặc mở công cụ 200 KB. Kết quả được kiểm tra theo bytes thật; nếu chưa đạt, cho phép giảm kích thước hoặc đổi sang JPG/WebP.'], ['Ảnh có được upload không?', 'Không. Các file được xử lý trong browser. Website chỉ tải mã nguồn, font và bộ giải mã cần thiết.'], ['Có thể xử lý nhiều ảnh cùng lúc không?', 'Có, tối đa 50 ảnh mỗi batch. Ảnh được xử lý lần lượt để giảm áp lực bộ nhớ; sau đó tải từng file hoặc ZIP.']] },
    en: { path: '/en/', title: 'Free Image Compressor — JPG, PNG & WebP | AnhGon', h1: 'Compress images. Keep them private.', description: 'Compress, convert and resize JPG, PNG, WebP and HEIC images in your browser. Free batch image tools with no sign-up and no image uploads.', intro: 'Compress, convert and resize a batch of images right in your browser. Choose your files, check the results and download — your images never leave your device.', label: 'Image compressor', steps: ['Choose quality, output format and optional maximum dimensions.', 'Add one or more images. Files are processed one at a time on your device.', 'Review the file sizes and previews, then download individual images or a ZIP.'], notes: ['Choose JPG for photos, PNG for transparent graphics, or WebP for website images.', 'File size and pixel dimensions are different. Reducing both can help meet an upload limit.', 'Keep your originals: compression may lose detail, EXIF is removed and animated images become still images.'], faq: [['Can I compress an image to 200 KB?', 'Choose the file-size mode or open the 200 KB tool. Results are checked in bytes. If the target is missed, allow smaller dimensions or choose JPG/WebP.'], ['Are my images uploaded?', 'No. Files are processed in your browser. The website only downloads its code, fonts and the decoders you need.'], ['Can I process a whole batch?', 'Yes, up to 50 images per batch. Images are processed sequentially to reduce memory pressure; download them individually or together as a ZIP.']] }
  },
  {
    id: '200kb', preset: { mode: 'target', target: 200, unit: 'KB', format: 'image/jpeg' },
    vi: { path: '/nen-anh-200kb/', title: 'Nén ảnh xuống 200 KB miễn phí | Ảnh Gọn', h1: 'Nén ảnh theo mục tiêu 200 KB', label: 'Nén ảnh 200 KB', description: 'Giảm dung lượng ảnh theo mục tiêu 200 KB để gửi biểu mẫu. Kiểm tra bytes thực tế, điều chỉnh kích thước và tải JPG ngay trên thiết bị.', intro: 'Chuẩn bị ảnh cho biểu mẫu giới hạn dung lượng. Mục tiêu 200 KB và đầu ra JPG đã được chọn sẵn; công cụ báo rõ ảnh có đạt giới hạn hay chưa.', steps: ['Giữ mục tiêu 200 KB hoặc nhập giới hạn biểu mẫu yêu cầu.', 'Chọn ảnh. Nếu muốn, bật cho phép giảm kích thước để tăng khả năng đạt mục tiêu.', 'Chỉ dùng kết quả có nhãn đạt mục tiêu. Kiểm tra ảnh rõ và đúng pixel yêu cầu trước khi gửi.'], notes: ['200 KB ở đây là 200.000 bytes. Dung lượng hiển thị được tính cùng một hệ đơn vị.', 'Nén theo chất lượng không luôn đủ. Một ảnh nhiều chi tiết có thể cần giảm số pixel.', 'Đầu ra JPG có nền trắng; nếu cần trong suốt, chọn WebP/PNG và kiểm tra lại dung lượng.', 'Biểu mẫu có thể yêu cầu cả pixel, tỷ lệ và định dạng. Đạt 200 KB chưa có nghĩa đáp ứng mọi điều kiện.'], faq: [['Tại sao ảnh vẫn lớn hơn 200 KB?', 'Có thể ảnh quá nhiều chi tiết hoặc bạn đang giữ nguyên số pixel. Cho phép giảm kích thước, chọn JPG/WebP rồi thêm lại ảnh để xử lý.'], ['Có thể chọn 100 KB hoặc 50 KB không?', 'Có. Đổi số ở dung lượng mục tiêu; bạn không cần chuyển trang. Công cụ luôn so kết quả với giới hạn bạn nhập.'], ['Nén xuống 200 KB có làm mờ ảnh không?', 'Có thể. Nén mất dữ liệu và giảm pixel đều có thể làm mất chi tiết. Kiểm tra khuôn mặt, chữ và các vùng quan trọng trước khi dùng.']] },
    en: { path: '/en/compress-image-to-200kb/', title: 'Compress Image to 200 KB Online Free | AnhGon', h1: 'Compress an image to a 200 KB target', label: 'Compress to 200 KB', description: 'Reduce images to a 200 KB target for upload forms. Check the actual byte limit, adjust dimensions and download JPG files privately in your browser.', intro: 'Get an image ready for a size-limited upload form. The 200 KB target and JPG output are already selected. Every result shows whether it meets the limit.', steps: ['Keep the 200 KB target or enter the limit your form requires.', 'Choose your images. Enable smaller dimensions if you want the tool to resize to fit.', 'Use a result marked within target. Check clarity and required pixel dimensions before submitting.'], notes: ['200 KB means 200,000 bytes here. Displayed sizes use the same decimal units.', 'Lower quality is not always enough. A detailed image may also need fewer pixels.', 'JPG uses a white background. Choose WebP/PNG if transparency matters and recheck the result.', 'Forms can require specific dimensions, aspect ratios and formats as well as file size.'], faq: [['Why is the result still over 200 KB?', 'The image may be too detailed while retaining its dimensions. Allow smaller dimensions, choose JPG/WebP and add the image again.'], ['Can I use a 100 KB or 50 KB limit?', 'Yes. Edit the target size without leaving this page. Results are always checked against the limit you entered.'], ['Will the image lose quality?', 'It can. Lossy compression and reduced pixel dimensions can remove detail. Review faces, text and important areas before using the result.']] }
  },
  {
    id: 'heic', preset: { format: 'image/jpeg' },
    vi: { path: '/heic-sang-jpg/', title: 'Chuyển HEIC sang JPG miễn phí, không upload | Ảnh Gọn', h1: 'Chuyển ảnh HEIC sang JPG', label: 'HEIC sang JPG', description: 'Đổi ảnh HEIC, HEIF từ iPhone sang JPG ngay trong browser. Chọn nhiều ảnh, kiểm tra kết quả và tải ZIP mà không upload ảnh lên server.', intro: 'Mở ảnh iPhone ở định dạng dễ chia sẻ hơn. Chọn file HEIC hoặc HEIF; đầu ra JPG đã sẵn sàng và ảnh được xử lý ngay trên thiết bị.', steps: ['Chọn file HEIC/HEIF từ ứng dụng Files hoặc thư mục ảnh gốc.', 'Chờ bộ giải mã tải ở lần đầu, sau đó ảnh được chuyển lần lượt sang JPG.', 'Kiểm tra chiều xoay, màu sắc và độ nét. Tải JPG hoặc cả batch dưới dạng ZIP.'], notes: ['Một số thiết bị tự đổi HEIC sang JPG khi chọn từ thư viện ảnh. Dùng Files nếu cần chọn đúng file HEIC gốc.', 'Ảnh HEIC độ phân giải cao cần nhiều bộ nhớ. Bắt đầu với một vài ảnh trên điện thoại.', 'Live Photo không được giữ chuyển động; metadata/EXIF không được mang sang kết quả.'], faq: [['Lần đầu chuyển HEIC có cần internet không?', 'Có, để tải bộ giải mã. Dùng chức năng lưu công cụ offline khi còn mạng để chuẩn bị dùng sau.'], ['Tại sao một file HEIC không mở được?', 'File có thể hỏng, dùng tính năng codec chưa được hỗ trợ hoặc quá lớn cho bộ nhớ thiết bị. Thử xuất JPG từ thiết bị gốc hoặc dùng batch nhỏ hơn.'], ['Có giữ nguyên chất lượng không?', 'Chuyển sang JPG là quá trình nén mất dữ liệu. Có thể tăng chất lượng nhưng dung lượng thường tăng theo.']] },
    en: { path: '/en/heic-to-jpg/', title: 'HEIC to JPG Converter — Free & Private | AnhGon', h1: 'Turn HEIC photos into JPG', label: 'HEIC to JPG', description: 'Convert iPhone HEIC and HEIF photos to JPG in your browser. Batch conversion and ZIP downloads, with no sign-up or image uploads.', intro: 'Make iPhone photos easier to share. Choose your HEIC or HEIF files; JPG output is ready to go, and conversion happens on your own device.', steps: ['Choose original HEIC/HEIF files from Files or your photo folder.', 'Let the decoder load on first use, then photos convert one at a time.', 'Check orientation, colors and detail. Download individual JPG files or a ZIP.'], notes: ['Some devices convert HEIC automatically when selecting from the photo library. Use the Files picker to select the original HEIC.', 'High-resolution HEIC images need memory. Start with a small batch on your phone.', 'Live Photo motion is not preserved, and EXIF metadata is removed.'], faq: [['Does first use need an internet connection?', 'Yes, to download the decoder. Save the tools for offline use while connected if you will need them later.'], ['Why does a HEIC file fail?', 'It may be damaged, use an unsupported codec feature or exceed device memory. Try exporting JPG from the original device or use a smaller batch.'], ['Is conversion lossless?', 'JPG uses lossy compression. Increasing quality can retain more detail, usually at the cost of a larger file.']] }
  },
  {
    id: 'webp', preset: { format: 'image/webp' },
    vi: { path: '/doi-anh-sang-webp/', title: 'Đổi JPG, PNG sang WebP miễn phí | Ảnh Gọn', h1: 'Chuẩn bị ảnh WebP cho website', label: 'Đổi sang WebP', description: 'Chuyển JPG, PNG và ảnh khác sang WebP. Tùy chỉnh chất lượng, giữ nền trong suốt và giới hạn kích thước ngay trên thiết bị.', intro: 'Chuyển ảnh sang WebP, chọn chất lượng và giới hạn số pixel phù hợp trang web. Xem dung lượng thực tế trước khi thay ảnh gốc.', steps: ['Chọn chất lượng và chiều rộng hoặc cao tối đa website cần.', 'Thêm ảnh JPG/PNG. WebP được chọn sẵn làm đầu ra.', 'So sánh dung lượng, kiểm tra nền trong suốt và tải kết quả phù hợp.'], notes: ['PNG trong suốt có thể chuyển sang WebP giữ alpha; chuyển sang JPG sẽ mất alpha.', 'WebP không luôn nhỏ hơn mọi ảnh gốc. Kiểm tra số bytes thay vì chỉ nhìn đuôi file.', 'Ảnh 4.000 px cho vị trí hiển thị nhỏ thường chưa cần thiết. Resize có thể giúp giảm đáng kể dung lượng.'], faq: [['WebP có giữ nền trong suốt không?', 'Có khi ảnh gốc có alpha. Kiểm tra bản xem trước và dùng file kết quả trên nền sáng/tối của website.'], ['Ảnh WebP có luôn nhẹ hơn JPG không?', 'Không. Kết quả phụ thuộc nội dung, chất lượng và encoder của browser. Công cụ ghi rõ khi output lớn hơn input.'], ['Có đổi nhiều ảnh sang WebP được không?', 'Có, tối đa 50 ảnh mỗi batch; có thể tải chung dưới dạng ZIP.']] },
    en: { path: '/en/convert-to-webp/', title: 'Convert JPG & PNG to WebP Free | AnhGon', h1: 'WebP images, ready for your website', label: 'Convert to WebP', description: 'Convert JPG, PNG and other images to WebP. Adjust quality, preserve transparency and resize for your website without uploading images.', intro: 'Choose the quality and pixel dimensions your website needs, then convert to WebP. Check the actual size before replacing your original.', steps: ['Choose quality and an optional maximum width or height.', 'Add JPG/PNG images. WebP output is already selected.', 'Compare sizes, check transparency and download the results that work for you.'], notes: ['Transparent PNG can become WebP with alpha; JPG does not preserve transparency.', 'WebP is not always smaller than the original. Compare bytes, not just extensions.', 'A 4,000 px image may be unnecessary for a small display area. Resizing can reduce the file size considerably.'], faq: [['Does WebP preserve transparency?', 'Yes, when the source contains alpha. Check the preview and test the output on the light/dark backgrounds of your website.'], ['Is WebP always smaller than JPG?', 'No. Results depend on the image, quality and browser encoder. The tool flags outputs larger than the original.'], ['Can I convert multiple images?', 'Yes, up to 50 images per batch, with a ZIP download for the results.']] }
  },
  {
    id: 'webp-jpg', preset: { format: 'image/jpeg' },
    vi: { path: '/webp-sang-jpg/', title: 'Chuyển WebP sang JPG miễn phí | Ảnh Gọn', h1: 'Đổi WebP sang JPG để dễ sử dụng', label: 'WebP sang JPG', description: 'Chuyển file WebP sang JPG để mở trong phần mềm hoặc gửi biểu mẫu. Nền trắng cho ảnh trong suốt, xử lý batch riêng tư trong browser.', intro: 'Cần JPG cho phần mềm hoặc biểu mẫu của bạn? Chọn ảnh WebP và chuyển ngay trên thiết bị, không cần đăng ký.', steps: ['Giữ định dạng đầu ra JPG và chọn chất lượng phù hợp.', 'Thêm ảnh WebP, hoặc dán ảnh từ clipboard nếu ứng dụng hỗ trợ.', 'Kiểm tra nền trắng và độ nét. Tải ảnh JPG về để dùng trong ứng dụng của bạn.'], notes: ['Đổi đuôi .webp thành .jpg không chuyển định dạng. Công cụ này giải mã rồi tạo file JPG thực sự.', 'Vùng trong suốt được ghép lên nền trắng. Chọn PNG nếu bạn muốn giữ alpha.', 'JPG có thể lớn hơn WebP; việc chuyển nhằm tương thích, không đảm bảo giảm dung lượng.'], faq: [['Có giữ nền trong suốt không?', 'JPG không có alpha. Công cụ dùng nền trắng; nếu cần trong suốt, chọn PNG ở định dạng đầu ra.'], ['Vì sao JPG lớn hơn WebP gốc?', 'Hai định dạng có cách nén khác nhau. Giảm chất lượng hoặc số pixel nếu bạn còn cần giảm dung lượng.'], ['WebP động có chuyển được không?', 'Có thể tạo một ảnh tĩnh từ file mà browser giải mã được; chuyển động sẽ không được giữ.']] },
    en: { path: '/en/webp-to-jpg/', title: 'WebP to JPG Converter — Free, No Upload | AnhGon', h1: 'Make your WebP images work as JPG', label: 'WebP to JPG', description: 'Convert WebP images to JPG for apps and upload forms. White backgrounds for transparent images, private batch processing and ZIP downloads.', intro: 'Need a JPG for an app or upload form? Choose your WebP images and convert them on your device, with no account required.', steps: ['Keep JPG output selected and choose your preferred quality.', 'Add WebP files, or paste an image from the clipboard when supported.', 'Check the white background and detail, then download the JPG results.'], notes: ['Renaming .webp to .jpg does not convert a file. This tool decodes the image and creates an actual JPG.', 'Transparent areas are placed on white. Choose PNG output if you need to keep alpha.', 'JPG may be larger than WebP. This conversion improves compatibility, not necessarily file size.'], faq: [['Can JPG keep a transparent background?', 'JPG does not support alpha. The tool uses white; select PNG output if you need transparency.'], ['Why is my JPG bigger than the original?', 'The formats compress differently. Reduce quality or pixel dimensions if you also need a smaller file.'], ['What happens to animated WebP?', 'A browser-decodable file can become a still image. Animation is not preserved.']] }
  }
];

export const infoPages = {
  about: {
    vi: { path: '/gioi-thieu/', title: 'Giới thiệu Ảnh Gọn', paragraphs: ['Ảnh Gọn (AnhGon) là bộ công cụ miễn phí để nén, chuyển định dạng và thay đổi kích thước ảnh trong browser. Mục tiêu là giúp bạn chuẩn bị ảnh cho biểu mẫu, chia sẻ và website bằng vài thao tác rõ ràng.', 'Dự án phát triển từ MAZANOKE của civilblur và sử dụng các thư viện open source. Mã nguồn fork và danh sách attribution được công khai ở footer. Đây là dự án độc lập, không phải website chính thức của MAZANOKE.', 'Có thể xử lý JPG, PNG, WebP, HEIC/HEIF, AVIF, TIFF, GIF, SVG và ICO khi decoder hỗ trợ file. Giới hạn hiện tại: 50 file/batch, 50 MB/file và 40 megapixel. Khả năng xử lý còn phụ thuộc bộ nhớ thiết bị.', 'Báo lỗi qua GitHub Issues trong liên kết mã nguồn. Hãy mô tả browser, định dạng và bước tái hiện; không gửi ảnh riêng tư.'] },
    en: { path: '/en/about/', title: 'About AnhGon', paragraphs: ['AnhGon is a free set of browser tools for compressing, converting and resizing images. It helps prepare images for forms, sharing and websites with a clear, short workflow.', 'The project builds on MAZANOKE by civilblur and open-source libraries. The fork source and attributions are linked below. This is an independent project, not the official MAZANOKE website.', 'Supported inputs include JPG, PNG, WebP, HEIC/HEIF, AVIF, TIFF, GIF, SVG and ICO when the decoder supports the file. Current limits: 50 files per batch, 50 MB per file and 40 megapixels. Device memory also affects what can be processed.', 'Report bugs through GitHub Issues on the source repository. Include your browser, format and reproduction steps; do not send private images.'] }
  },
  privacy: {
    vi: { path: '/quyen-rieng-tu/', title: 'Quyền riêng tư — Ảnh Gọn', paragraphs: ['Ảnh bạn chọn, dán và kết quả được xử lý trong bộ nhớ browser trên thiết bị. Website không có endpoint nhận ảnh và không gửi nội dung ảnh hoặc tên file lên server.', 'Website tải HTML, JavaScript, font và thư viện từ hosting. Netlify có thể ghi log kỹ thuật như địa chỉ IP, URL và user agent để cung cấp dịch vụ. Phiên bản này không tích hợp quảng cáo, cookie tracking hoặc analytics bên thứ ba.', 'Browser có thể lưu tùy chỉnh và theme trong localStorage, mã nguồn trong service worker cache để dùng offline. Không lưu ảnh của bạn trong các cache đó. Bạn có thể xóa dữ liệu website trong phần cài đặt browser.', 'Xóa kết quả hoặc rời trang sẽ giải phóng các tham chiếu ảnh trong ứng dụng. File bạn chủ động tải về được quản lý bởi browser và thiết bị của bạn. Nén/chuyển ảnh loại EXIF; luôn giữ bản gốc khi cần metadata.', 'Chính sách sẽ được cập nhật nếu cách thu thập dữ liệu thay đổi. Cập nhật ngày 27/09/2026.'] },
    en: { path: '/en/privacy/', title: 'Privacy — AnhGon', paragraphs: ['Images you select or paste, and their results, are processed in browser memory on your device. This website has no image-upload endpoint and does not send image contents or filenames to a server.', 'The website downloads HTML, JavaScript, fonts and libraries from its hosting provider. Netlify may keep technical access logs such as IP addresses, URLs and user agents to operate its service. This version has no advertising, tracking cookies or third-party analytics.', 'Your browser may save settings and theme in localStorage and application code in a service worker cache for offline use. Your images are not stored in those caches. You can remove website data in your browser settings.', 'Clearing results or leaving the page releases application references to images. Files you download are managed by your browser and device. Compression/conversion removes EXIF; keep originals if you need their metadata.', 'This policy will be updated if data collection changes. Updated September 27, 2026.'] }
  }
};
